package java8;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class flatMap {
	
	public static void main(String[] args) {
		
		 List<String> memberNames = new ArrayList<>();
         memberNames.add("Amitabh");
         memberNames.add("Shekhar");
         memberNames.add("Aman");
         memberNames.add("Rahul");
         memberNames.add("Shahrukh");
         memberNames.add("Salman");
         memberNames.add("Yana");
         memberNames.add("Lokesh");
         
         
         List listOfInts = memberNames.stream() .map(s -> s.length()) .collect(Collectors.toList()); 
         
         System.out.println("list of ints generate by map(): " + listOfInts); 
         // flatMap() example, let's first creat a list of list 
         List<List> listOfListOfNumber = new ArrayList<>(); 
         listOfListOfNumber.add(Arrays.asList(2, 4));
         listOfListOfNumber.add(Arrays.asList(3, 9)); 
         listOfListOfNumber.add(Arrays.asList(4, 16));
         
         System.out.println("list of list : " + listOfListOfNumber); 
         List listOfIntegers =  (List) listOfListOfNumber.stream().flatMap(list -> list.stream()).collect(Collectors.toList());
         // let's use flatMap() to flatten this list into // list of integers i.e. 2,4,3,9,4,16
        /* List listOfIntegers = listOfListOfNumber.stream() 
        		 .flatMap( list -> list.stream())
        		 .collect(Collectors.toList()); */
         System.out.println("list of numbers generated by flatMap : " + listOfIntegers);

      // 
		
	}

}
